apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-client
spec:
  selector:
    matchLabels:
      app: cloud-client
  template:
    metadata:
      labels:
        app: cloud-client
    spec:
      containers:
      - name: cloud-client
        image: rheny/cloud-client:v0.2
        resources:
          requests:
            memory: "20Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
