apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-server
spec:
  selector:
    matchLabels:
      app: cloud-server
  template:
    metadata:
      labels:
        app: cloud-server
    spec:
      containers:
      - name: cloud-server
        image: rheny/cloud-server:v0.1
        env:
          - name: API_VERSION
            value: v1.1
        resources:
          requests:
            memory: "20Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
